# site properties and page defaults
title: emad askarinejad
subtitle: 
description: 
header: images/banner.jpg
footer: images/banner.jpg

# site social media and other links
links:
  email: emad.askarinejad@mail.mcgill.ca
  # orcid: 0000-0001-8713-9213
  google-scholar: https://scholar.google.com/citations?user=qUZIvvwAAAAJ&hl=en
  linkedin: emad-askari
  github: emad-askari
  # twitter: emad-askari
  # youtube: emad-askari

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
